### ISSUE TITLE
Download the modified scikit_image package

### ISSUE THREAD

**Issue by pppkkk611** [SJTU-ViSYS/StructDepth#1]
Thank you for your outstanding work, please approve your Google drive permissions. I need download the modified scikit_image package ，pretrained model and test dataset. Thank you again.

**Comment by huangyuan2020** [comment]
> Thank you for your outstanding work, please approve your Google drive permissions. I need download the modified scikit_image package ，pretrained model and test dataset. Thank you again.

Thanks for your reminding. The permission has been updated. Please try to download it.

**Comment by pppkkk611** [comment]
thanks ，but after i unzip the scikit-image-0.17.2.zip and run the execute python setup.py build_ext -i, the following conditions will occur：

skimage/io/_plugins/_histograms.c:2077:31: 错误：‘PyArrayObject {或称 struct tagPyArrayObject}’没有名为‘dimensions’的成员
   __pyx_v_width = (__pyx_v_img->dimensions[1]);
                               ^~
skimage/io/_plugins/_histograms.c:2086:32: 错误：‘PyArrayObject {或称 struct tagPyArrayObject}’没有名为‘dimensions’的成员
   __pyx_v_height = (__pyx_v_img->dimensions[0]);
                                ^~
error: Command "gcc -pthread -B /home/apple/anaconda3/envs/struct_depth/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/apple/anaconda3/envs/struct_depth/lib/python3.6/site-packages/numpy/core/include -I/home/apple/anaconda3/envs/struct_depth/lib/python3.6/site-packages/numpy/core/include -I/home/apple/anaconda3/envs/struct_depth/include/python3.6m -c skimage/io/_plugins/_histograms.c -o build/temp.linux-x86_64-3.6/skimage/io/_plugins/_histograms.o -MMD -MF build/temp.linux-x86_64-3.6/skimage/io/_plugins/_histograms.o.d -fopenmp" failed with exit status 1

**Comment by huangyuan2020** [comment]
This seems to be a compilation problem, you can check cython and other environments to see if they are working. The version I am using is Cython Version 0.29.15, which compiles properly.
