### ISSUE TITLE
Need help for the depth estimation visualization

### ISSUE THREAD

**Issue by zhyever** [SJTU-ViSYS/StructDepth#2]
Thanks for the outstanding work! When I read your paper, I noticed Figure S2, an extremely intuitive representation of the depth estimation result. I wonder how to draw such images? Given the prediction and the input image, what else do I need? Camera parameters or something else?
Furthermore, what tool and application can I utilize? I'm new in this area. I will appreciate your hints a lot!!!

**Comment by huangyuan2020** [comment]
Yes, you need to use the camera parameters to restore the point cloud from the depth map, just like the Backproject class we used during training,  and then assign color to each point to get a colored point cloud file, and then open it with a software like meshlab, you can see the effect in Figure S2.

```
def generate_pointcloud_ply(xyz, color, pc_file):
    # how to generate a pointcloud .ply file using xyz and color
    # xyz    ndarray  3,N  float
    # color  ndarray  3,N  uint8
    df = np.zeros((6, xyz.shape[1]))
    df[0] = xyz[0]
    df[1] = xyz[1]
    df[2] = xyz[2]
    df[3] = color[0]
    df[4] = color[1]
    df[5] = color[2]
    float_formatter = lambda x: "%.4f" % x
    points =[]
    for i in df.T:
        points.append("{} {} {} {} {} {} 0\n".format
                      (float_formatter(i[0]), float_formatter(i[1]), float_formatter(i[2]),
                       int(i[3]), int(i[4]), int(i[5])))
    file = open(pc_file, "w")
    file.write('''ply
    format ascii 1.0
    element vertex %d
    property float x
    property float y
    property float z
    property uchar red
    property uchar green
    property uchar blue
    property uchar alpha
    end_header
    %s
    ''' % (len(points), "".join(points)))
    file.close()
```

**Comment by huangyuan2020** [comment]
> Thanks for the outstanding work! When I read your paper, I noticed Figure S2, an extremely intuitive representation of the depth estimation result. I wonder how to draw such images? Given the prediction and the input image, what else do I need? Camera parameters or something else? Furthermore, what tool and application can I utilize? I'm new in this area. I will appreciate your hints a lot!!!

Yes, you need to use the camera parameters to restore the point cloud from the depth map, just like the Backproject class we used during training,  and then assign color to each point to get a colored point cloud file, and then open it with a software like meshlab, you can see the effect in Figure S2.

```
def generate_pointcloud_ply(xyz, color, pc_file):
    # how to generate a pointcloud .ply file using xyz and color
    # xyz    ndarray  3,N  float
    # color  ndarray  3,N  uint8
    df = np.zeros((6, xyz.shape[1]))
    df[0] = xyz[0]
    df[1] = xyz[1]
    df[2] = xyz[2]
    df[3] = color[0]
    df[4] = color[1]
    df[5] = color[2]
    float_formatter = lambda x: "%.4f" % x
    points =[]
    for i in df.T:
        points.append("{} {} {} {} {} {} 0\n".format
                      (float_formatter(i[0]), float_formatter(i[1]), float_formatter(i[2]),
                       int(i[3]), int(i[4]), int(i[5])))
    file = open(pc_file, "w")
    file.write('''ply
    format ascii 1.0
    element vertex %d
    property float x
    property float y
    property float z
    property uchar red
    property uchar green
    property uchar blue
    property uchar alpha
    end_header
    %s
    ''' % (len(points), "".join(points)))
    file.close()
```

**Comment by zhyever** [comment]
Thanks! I will have a try.

**Comment by stefanklut** [comment]
Hi there,

Could you please tell me what camera intrinsic are used for the pretrained models? I would like to see some depth results on a custom input in the form of a pointcloud. It is unclear to me what intrinsics I should use for these images: the values found in nyu_dataset? and with or without crop? Also what is the purpose of dividing by height and width?

Thanks in advance for your help
