### ISSUE TITLE
How could I get the color and geometry dissimilarity maps?

### ISSUE THREAD

**Issue by EchoTHChen** [SJTU-ViSYS/StructDepth#4]
Hi, I'm curious about how can I get the color + geometry dissimilarity maps?

**Comment by EchoTHChen** [comment]
I did not find the code for that part. Could you help me?

**Comment by huangyuan2020** [comment]
> I did not find the code for that part. Could you help me?

Please refer to [trainer.py L454-L515](https://github.com/SJTU-ViSYS/StructDepth/blob/17478278c228662248772c9a0c94d553d20078c5/trainer.py#L454-L515), this function completes the calculation of the color + geometry dissimilarity maps and the generation of the plane detection result.
